backend:
  name: git-gateway
  branch: master

# display_url: 
# logo_url: 
public_folder: '/images'
media_folder: 'source/images'
# media_library:
#   name: uploadcare
#   config:
#     publicKey: 

collections:
  - name: 'pages'
    label: 'Pages'
    editor:
      preview: false
    files:
      - label: 'Page One'
        name: 'one'
        file: 'pages/one.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Slug', name: 'slug', widget: 'hidden', default: 'one' }
          - { label: 'Summary', name: 'summary', hint: 'I am a field hint', widget: 'text' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
      
      - label: 'FAQ'
        name: 'faq'
        file: 'pages/faq.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Slug', name: 'slug', widget: 'hidden', default: 'faq' }
          - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'faq' }
          - { label: 'Tags', name: 'tags', widget: 'hidden', default: 'nav' }
          - label: 'Questions'
            name: 'questions'
            widget: 'list'
            fields:
              - { label: 'Question', name: 'question', widget: 'string' }
              - { label: 'Answer', name: 'answer', widget: 'text' }



  # - name: 'posts'
  #   label: 'Posts'
  #   label_singular: 'Post'
  #   editor:
  #     preview: false
  #   description: The description is a great place for high level information, and editing guidelines that are specific to this collection.
  #   create: true
  #   folder: 'posts'
  #   slug: '{{slug}}'
  #   fields:
  #     - { label: 'Title', name: 'title', widget: 'string' }
  #     - { label: 'Body', name: 'body', widget: 'markdown' }